### ISSUE TITLE
Day Cares broken in stock Essentials v19.1 with Hotfixes v1.0.7 plugin

### ISSUE THREAD

**Issue by M1CR0H4CK3R** [Maruno17/pokemon-essentials#141]
`[Pokémon Essentials version 19.1]
[Generation 8 Project v1.1.0]
[v19.1 Hotfixes 1.0.7]

Exception: RuntimeError
Message: Script error in event 3 (coords 4,4), map 472 (Lavaridge Day Care):
Exception: NoMethodError
Message: undefined method `isSpecies?' for nil:NilClass

***Full script:
pbDayCareDeposit(pbGet(1))

Backtrace:
221:Overworld_DayCare:55:in `block in pbDayCareDeposit'
221:Overworld_DayCare:51:in `each'
221:Overworld_DayCare:51:in `pbDayCareDeposit'
(eval):1:in `execute_script'
033:Interpreter:137:in `eval'
033:Interpreter:137:in `execute_script'
034:Interpreter_Commands:1030:in `command_355'
034:Interpreter_Commands:116:in `execute_command'
033:Interpreter:127:in `block in update'
033:Interpreter:87:in `loop'

Backtrace:
033:Interpreter:189:in `rescue in execute_script'
033:Interpreter:135:in `execute_script'
034:Interpreter_Commands:1030:in `command_355'
034:Interpreter_Commands:116:in `execute_command'
033:Interpreter:127:in `block in update'
033:Interpreter:87:in `loop'
033:Interpreter:87:in `update'
032:Scene_Map:157:in `block in update'
032:Scene_Map:155:in `loop'
032:Scene_Map:155:in `update'
`

The error happens immediately upon choosing a Pokemon. First a blank text box opens, and upon closing it I get the above error.

The error above is from a town in my game, but the error also happens in the example maps, namely Lerucean Town's Day Care.

If this has been fixed in a newer version of the hotfixes plugin, please notify me and close this issue.

**Comment by M1CR0H4CK3R** [comment]
Turns out it's an issue with the latest Generation 8 Project's compatibility, but the error is so vague and unhelpful, so I cannot diagnose the issue.

**Comment by Maruno17** [comment]
I'm closing this because the error message includes third party content (namely, the Generation 8 Project plugin). Reopen this report if you can replicate this error without that plugin.

**Comment by M1CR0H4CK3R** [comment]
The default Day Care Lady event in Lerucean Town has several outdated script methods, one of which was causing the crash in question. I figured out the correct syntax of the event and remade it so it works, but you really should test your own Day Care Lady.
