### ISSUE TITLE
Symbiosis

### ISSUE THREAD

**Issue by Hokath** [Maruno17/pokemon-essentials#148]
https://github.com/Maruno17/pokemon-essentials/blob/19535b81607aca2aad4d364e7afaeab41e560dc9/Data/Scripts/011_Battle/001_Battler/006_Battler_AbilityAndItem.rb#L164

It seems that because opposes? defaults to index=0, symbiosis cannot trigger for the opposing team.
So it needs to be "opposes?(self)" here instead.

p.s. I also had to rename pbSymbiosis. I have no idea why, it just wouldn't fire without the rename (I could write puts "hello world" at the start and it wouldn't even print. No idea why this was, never seen that before).

**Comment by Maruno17** [comment]
Fixed.

You had to rename `def pbSymbiosis` because that method is also in the v19.1 Hotfixes plugin, so changes to the original `def pbSymbiosis` wouldn't have made a difference.

**Comment by Hokath** [comment]
Ah that makes sense! Silly me, didn't think about that.
