### ISSUE TITLE
Incinerate text

### ISSUE THREAD

**Issue by Hokath** [Maruno17/pokemon-essentials#153]
https://github.com/Maruno17/pokemon-essentials/blob/19535b81607aca2aad4d364e7afaeab41e560dc9/Data/Scripts/011_Battle/002_Move/006_Move_Effects_080-0FF.rb#L3371-L3372

I suspect the ordering of these two lines should be swapped!
This way, no message is displayed because the item is already gone when it writes.

**Comment by Maruno17** [comment]
Fixed.
