### ISSUE TITLE
Map Connection with Events on border can cause stack level too deep?

### ISSUE THREAD

**Issue by jianmingyong** [Maruno17/pokemon-essentials#181]
Update: It seems like putting any Event on the border of the map (in certain order) will cause the game to crash when they are connected.

How to reproduce:
Case A:
```
Map A => Map B (Connected from A to B)
```
In the example above, if you have a map connection between A and B, if you have an event at the right border of Map B, the game simply crashes.

Case B:
```
Map B  (Connected from A to B)
   ^
Map A (Main map)
```
In this case, if you have an event on the top border of Map B, it would crash.

The direction in which the connection is made would mean that the connected map's border can't have an event at all.

Official logs... without modification.
```
[2022-05-30 23:01:44 +0800]
[Pokémon Essentials version 20]

Exception: SystemStackError
Message: stack level too deep

Backtrace:
```

**Comment by Maruno17** [comment]
Fixed.
