### ISSUE TITLE
Screen goes black after battle, except overworld events

### ISSUE THREAD

**Issue by Titania318** [Maruno17/pokemon-essentials#182]
I am using a clean copy of Base Essentials plus the v20 Hotfixes plugin 1.0.3 only. After battling, part of the screen goes black. I have attached a before and after image. After moving away from the black part and coming back, the black part no longer appears.

Before:
![Before](https://user-images.githubusercontent.com/46846557/171907170-b7c644c3-c207-4c9d-8c3d-7301c89b78ac.PNG)

After:
![After](https://user-images.githubusercontent.com/46846557/171907169-63cdeb6a-e9b7-48b8-8064-5922b842b5f7.PNG)

.

**Comment by DerxwnaKapsyla** [comment]
Can confirm, bug is happening on my end as well. Here's a gif of it in action
https://imgur.com/iOifNZc

**Comment by Titania318** [comment]
Fixed. Thank you.
