### ISSUE TITLE
pbShowCommandsWithHelp softlock

### ISSUE THREAD

**Issue by Vendily** [Maruno17/pokemon-essentials#189]
https://github.com/Maruno17/pokemon-essentials/blob/d890cd8a2478f2466da22645156d5b1f46432b72/Data/Scripts/007_Objects%20and%20windows/011_Messages.rb#L822

`pbShowCommandsWithHelp` does not dispose its temp `msgwin` with `pbDisposeMessageWindow`. This means if no regular message is shown after it, which would also call `pbDisposeMessageWindow`, `$game_temp.message_window_showing` remains true from the last `pbCreateMessageWindow` call, blocking all user input.

**Comment by Maruno17** [comment]
Fixed in commit 88dc215.
