### ISSUE TITLE
Price when Selling items is halved a second time

### ISSUE THREAD

**Issue by Vendily** [Maruno17/pokemon-essentials#196]
https://github.com/Maruno17/pokemon-essentials/blob/d890cd8a2478f2466da22645156d5b1f46432b72/Data/Scripts/016_UI/020_UI_PokeMart.rb#L684

Basically, you end up selling items for a quarter of their buy price (as the default sell price is half, and the line above halves the sell price again).

**Comment by Maruno17** [comment]
This has already been fixed in the dev branch.
