### ISSUE TITLE
Use of $Trainer.setSeen results in pokedex error

### ISSUE THREAD

**Issue by Tastyredtomato** [Maruno17/pokemon-essentials#21]
After seeing a pokemon using the $Trainer.setSeen command, the game results in a crash when opening the pokedex and going to the map screen. Specific pokemon doesn't matter. 
Error message below. Confirmed to exist with multiple people.

![](https://cdn.discordapp.com/attachments/265382074020528128/756841845467906078/unknown.png)

**Comment by Maruno17** [comment]
This isn't a bug. Registering a Pokémon as seen in the Pokédex is a two step process, and using `$Trainer.setSeen` is just the first one, which unlocks the species as a whole. The second is to use `def pbSeenForm` to record a particular gender/form as seen.

Is there anywhere in Essentials that doesn't do both steps?

**Comment by Tastyredtomato** [comment]
Thank you for the swift response!
Will consider the issue solved.
