### ISSUE TITLE
Wiki URL should be deleted?

### ISSUE THREAD

**Issue by Th-eo** [Maruno17/pokemon-essentials#211]
https://github.com/Maruno17/pokemon-essentials/blob/dev/Essentials%20Docs%20Wiki.URL
Link is dead.
Donno if this mirror is officially-supported/maintained but it exists https://essentialsdocs.fandom.com/wiki/Essentials_Docs_Wiki

**Comment by Maruno17** [comment]
The shortcut itself works if you open it, and it points to the new wiki. Looks like it just contains some unused metadata that references the old wiki.

I'll replace the shortcut anyway, but it was never broken.
