### ISSUE TITLE
surfing graphic on invalid tile

### ISSUE THREAD

**Issue by noobkitteh** [Maruno17/pokemon-essentials#217]
surf graphic is shown in invalid tile if a map transfer happens while surfing (stops when the player moves)

https://github.com/Maruno17/pokemon-essentials/assets/122694772/d2ac3933-c899-4130-8403-22ef61e18de4

**Comment by Maruno17** [comment]
That doesn't happen if you do the map transfer the same way that doors work (which is how you're supposed to do map transfers).

**Comment by noobkitteh** [comment]
then i guess i did something wrong
