### ISSUE TITLE
Don't know how to open a pokemon essentials project.

### ISSUE THREAD

**Issue by AlejandroSocasAlvarez** [Maruno17/pokemon-essentials#220]
![image](https://github.com/Maruno17/pokemon-essentials/assets/108428465/51860001-17b7-4c6f-aa59-e1d59a0cb63f)
The tutorials that I have seen for pokemon essentials have an archive called Game.rx.proj which the creator of the videos says that it comes with the download, how do I start using pokemon essentials on RPG Maker XP?

**Comment by Maruno17** [comment]
This isn't a place to ask for help.

**Comment by AlejandroSocasAlvarez** [comment]
> This isn't a place to ask for help.

Then, where should I ask for help?
