### ISSUE TITLE
Issue with using the "Jump" command in the "Set Move Route" Menu.

### ISSUE THREAD

**Issue by Ftyari** [Maruno17/pokemon-essentials#30]
_After merging the latest commits from the master branch, the following error message pops up when any character tries to jump in place, i.e. the x+ and y+ coordinates are set to 0. Multiple people have reported the same problem in their games._ [Error Message](https://i.imgur.com/CaUjDh5.png)

_How to reproduce: Have any move route call the "Jump" function and set the coordinates to x+0 and y+0._
[Event](https://i.imgur.com/szAOWlI.png)

**Comment by kyurejl** [comment]
I thought i was the only one, i was already going crazy.

**Comment by Maruno17** [comment]
Should be resolved now.
