### ISSUE TITLE
LIGHTTEXT colors are not applied to dark windowskins in pbMessage

### ISSUE THREAD

**Issue by boonzeet** [Maruno17/pokemon-essentials#39]
![image](https://user-images.githubusercontent.com/6069095/96098212-c1f1d980-0ec9-11eb-9576-6b84f0702dba.png)

As shown in the above screenshot, `isDarkWindowskin` is used to set the text colors before the windowskin is set in the `pbMessageDisplay` routine, which results in always choosing the DARKTEXT colors. This also affects the use of `\c[0]`.

Moving \w out of the command loop and placing it with the text gsub routines, before the color assignment routine, will fix the issue

**Comment by Maruno17** [comment]
Resolved in pull request #40.
