### ISSUE TITLE
Control Timers visual bug

### ISSUE THREAD

**Issue by Tastyredtomato** [Maruno17/pokemon-essentials#58]
Has been tested in a fresh version of essentials.

Following event action sequence causes a visual bug where the timer isn't drawn on-screen:
-control timer startup (timer appears just fine)
-control timer stop (timer disappears as expected)
-control timer startup (subsequent timers no longer show up, however time is being kept correctly behind the scenes)

**Comment by Maruno17** [comment]
Fixed.
