### ISSUE TITLE
Toxic icon not updating proeprly

### ISSUE THREAD

**Issue by DerxwnaKapsyla** [Maruno17/pokemon-essentials#68]
When testing out Toxic Spikes and Toxic in v18.1.dev, I've noticed that the new indicator for the Toxic status doesn't actually display properly. Initially, it shows the regular poison icon. Even after taking damage it doesn't update the icon. It only updates the icon to the proper toxic icon after a Pokemon has been swapped out, or something of likely similar affect updates the battle scene.

[Video footage of the issue in action can be found here.](https://reliccastle.com/data/video/0/915-d6a21cfddca353ec8fce65f9228a001a.mp4)

**Comment by Maruno17** [comment]
Fixed.
