### ISSUE TITLE
Truant causes the opposing Pokemon to stop attacking after 3 activations

### ISSUE THREAD

**Issue by DerxwnaKapsyla** [Maruno17/pokemon-essentials#70]
When you use a Pokemon with Truant, after roughly three activations of the ability (aprox. 6 turns), the opposing Pokemon stops attacking entirely.
https://www.youtube.com/watch?v=j-XNq93tILM&feature=youtu.be

**Comment by Maruno17** [comment]
This has nothing to do with Truant. The bug is that a Pokémon cannot use Struggle ones it runs out of PP for its moves. This bug has been fixed.
