### ISSUE TITLE
Pokemon don't retain form upon evolution

### ISSUE THREAD

**Issue by JMcKinty96** [Maruno17/pokemon-essentials#73]
Pokémon do not retain their forms upon evolving, even if the form is forced through the debug menu.

Full context: A regional variant evolutionary line of a Pokémon is not retained upon evolving. For example, a Rattata-1 will not evolve in to a Raticate-1, but will revert to a Raticate-0. This seems to happen regardless of the specifics of getFormOnCreation. This also occurs with Pumpkaboo/Gourgeist, which was changed from a forced form 3 to form 0 upon evolving.

Edit: further testing has made it clear that the form is discarded somewhere during the evolution stage _after_ the function decides what sprite to show for the evolution screen. The Pokémon visually looks like the form they should have turned in to, but as soon as the evolution is completed it will start the new move learning process for their form 0 move set (if the move sets differ).

**Comment by JMcKinty96** [comment]
I mistakenly thought that this issue was only present in my version of the code, but I was using an outdated version of the 18.1 master from about 2~ weeks ago. The issue is definitely there in the current master.

**Comment by Maruno17** [comment]
Fixed.
