### ISSUE TITLE
Quirk: pbNoticePlayer doesn't really display over overworlds in base essentials

### ISSUE THREAD

**Issue by DerxwnaKapsyla** [Maruno17/pokemon-essentials#76]
This... Isn't really a bug per se, but it is an oddity with the way base Essentials works. basically, when pbNoticePlayer is on an event (at least, a trainer event), it displays the exclaim bubble over the center of the event, instead of over its head. Theoretically, a person could just add additional height over the overworld sprite, I think? However, as this is something involving Base Essentials, I felt it was worth bringing up. A potential fix would involve allowing the user to set an x/y coordinate for pbNoticeTrainer, making it much more malleable for larger/smaller events.

**Comment by Maruno17** [comment]
That's just a matter of how the animation was made. It also needs changing in other ways too, such as using different graphics.

**Comment by platinumphoenix2** [comment]
Subtracting 1 from sprite's y-values in def pbExlaim seems to fix it.
sprite = $scene.spriteset.addUserAnimation(id,i.x,i.**y-1**,tinting,2)
sprite = $scene.spriteset.addUserAnimation(id,event.x,event.**y-1**,tinting,2)

The animation plays fine when you use the event animation version, but its offset when pbNoticePlayer is used.

**Comment by Maruno17** [comment]
This has now been fixed. Playing a common animation via the event command is now identical to playing it via pbExclaim.
