### ISSUE TITLE
Single member party with an Illusion mon causes the pokemon to copy itself.

### ISSUE THREAD

**Issue by Vendily** [Maruno17/pokemon-essentials#90]
https://github.com/Maruno17/pokemon-essentials/blob/f3f21d4679a6d816aef7a1e57d79ab9e2992c5c1/Data/Scripts/012_Battle/003_Battle/002_PokeBattle_Battle.rb#L399

It seems to be related to this -1, as later down `ret = i if partyOrders[i]>partyOrders[ret]` would be `ret = i if partyOrders[0]>partyOrders[-1]` and in a single mon party, both of those are 0, and ret doesn't get changed from -1.

And since -1 != 0, Illusion copies the -1 slot, which is the first and only mon, itself.

Changing the linked line to `ret = 0` seems to resolve this issue with no effect to larger parties.

**Comment by Maruno17** [comment]
Fixed but in a different way.
