### ISSUE TITLE
Bug?: Evolution after being defeated in battle

### ISSUE THREAD

**Issue by DerxwnaKapsyla** [Maruno17/pokemon-essentials#92]
Tested on Essentials v18.1; if you have a Pokemon gain a level and it meets the requirements for evolution, then it faints in battle and you are totally defeated, the Pokemon will still evolve before you're sent back to the Pokemon Center/Home. I'm fairly certain this isn't base Pokemon mechanics? I don't remember seeing it in the v18 or 18.1 change log, so if it is I completely overlooked it.

Edit: There is one throwaway line on Bulbapedia that mentions that "Prior to Generation VI, the Pokémon will not be given the opportunity to evolve if player blacks out.". I guess that would make this not a bug, except I didn't see this change listed anywhere in the v18/18.1 change log.

**Comment by Maruno17** [comment]
Try as I might, the change log isn't exhaustive. I'm bound to miss things here and there. I haven't looked for whether this (or something similar to this) is mentioned anywhere in the change logs. It may have been implemented in an earlier version.

As you've said, this mechanic is only briefly mentioned on Bulbapedia. The dev version has settings for both "check for evolution even if the player loses the battle" (which seems to be what this feature is) and for "let fainted Pokémon evolve" (Bulbapedia even more briefly states this, and implies Pokémon that level up and then faint have always been able to evolve after the battle, which I didn't realise).

So as far as I can tell, this isn't a bug. I won't bother amending the master branch.

**Comment by DerxwnaKapsyla** [comment]
I have managed to get concrete evidence that it does indeed work like that, so yea this isn't a bug.
